/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.disenosoftwareproject.interfaz.vista;

import com.mycompany.disenosoftwareproject.interfaz.pares_vista_control.CtrlVistaIdentificarse;
import com.mycompany.disenosoftwareproject.interfaz.vista.VistaModificarOperadorEnTurno;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author el_pouleto
 */
public class VistaGerente extends javax.swing.JFrame {
    private CtrlVistaIdentificarse controlador = CtrlVistaIdentificarse.getInstance();
    /**
     * Creates new form VistaGerente
     */
    public VistaGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        consultarDatos = new javax.swing.JButton();
        consultarVacaciones = new javax.swing.JButton();
        organizarOperador = new javax.swing.JButton();
        modificarOperador = new javax.swing.JButton();
        organizarOperatorEmergencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gerente");

        consultarDatos.setText("Consultar mis datos en la empresa");
        consultarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarDatosActionPerformed(evt);
            }
        });

        consultarVacaciones.setText("Consultar vacaciones");
        consultarVacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVacacionesActionPerformed(evt);
            }
        });

        organizarOperador.setText("Organizar turnos de operador");
        organizarOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizarOperadorActionPerformed(evt);
            }
        });

        modificarOperador.setText("Modificar operador en turno");
        modificarOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarOperadorActionPerformed(evt);
            }
        });

        organizarOperatorEmergencia.setText("Organizar turnos de operativos de emergencia");
        organizarOperatorEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizarOperatorEmergenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(organizarOperador)
                    .addComponent(modificarOperador)
                    .addComponent(organizarOperatorEmergencia)
                    .addComponent(jLabel1)
                    .addComponent(consultarDatos)
                    .addComponent(consultarVacaciones))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(consultarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultarVacaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(organizarOperador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificarOperador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(organizarOperatorEmergencia)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        modificarOperador.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e){
                try {
                    controlador.modificarOperador();
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                    System.out.println(ex.getCause());
                }
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarDatosActionPerformed
        // Ne fait rien
    }//GEN-LAST:event_consultarDatosActionPerformed

    private void consultarVacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVacacionesActionPerformed
        // Ne fait rien
    }//GEN-LAST:event_consultarVacacionesActionPerformed

    private void organizarOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizarOperadorActionPerformed
        JFrame frame = new JFrame("Modificar Operador en Turno");
        frame.setContentPane(new VistaModificarOperadorEnTurno());
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_organizarOperadorActionPerformed

    private void modificarOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarOperadorActionPerformed
        // Ne fait rien
    }//GEN-LAST:event_modificarOperadorActionPerformed

    private void organizarOperatorEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizarOperatorEmergenciaActionPerformed
        // Ne fait rien
    }//GEN-LAST:event_organizarOperatorEmergenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarDatos;
    private javax.swing.JButton consultarVacaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modificarOperador;
    private javax.swing.JButton organizarOperador;
    private javax.swing.JButton organizarOperatorEmergencia;
    // End of variables declaration//GEN-END:variables
}
