/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.disenosoftwareproject.interfaz.pares_vista_control;

import javax.swing.JFrame;


public class ViewOperador extends javax.swing.JPanel {

    public ViewOperador(String rol) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        consultarDatos = new javax.swing.JButton();
        consultarVacaciones = new javax.swing.JButton();
        attenderLlamada = new javax.swing.JButton();

        jLabel1.setText("Operador");

        consultarDatos.setText("Consultar mis datos en la empresa");

        consultarVacaciones.setText("Consultar vacaciones");
        consultarVacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVacacionesActionPerformed(evt);
            }
        });

        attenderLlamada.setText("Attender llamada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultarVacaciones)
                            .addComponent(consultarDatos)
                            .addComponent(attenderLlamada))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(consultarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultarVacaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attenderLlamada)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void consultarDatosActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // Ne fait rien
    }                                              
    private void consultarVacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVacacionesActionPerformed
        // Ne fait rien
    }//GEN-LAST:event_consultarVacacionesActionPerformed

    /* A modifier quand nom de la 2e partie
    private void attenderLlamadaActionPerformed(){
    JFrame frame = new JFrame("Attender Llamada");
        frame.setContentPane(new Vista####());
        frame.pack();
        frame.setVisible(true);
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attenderLlamada;
    private javax.swing.JButton consultarDatos;
    private javax.swing.JButton consultarVacaciones;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
