/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.disenosoftwareproject.interfaz.pares_vista_control;


public class ViewPersonalDeOperativo extends javax.swing.JPanel {

    public ViewPersonalDeOperativo(String rol) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        consultarDatos = new javax.swing.JButton();
        consultarVacaciones = new javax.swing.JButton();
        consultarEmergencia = new javax.swing.JButton();
        consultarTurnos = new javax.swing.JButton();
        solicitarCambioTurno = new javax.swing.JButton();

        jLabel1.setText("Personal de Operativo");

        consultarDatos.setText("Consultar mis datos en la empresa");

        consultarVacaciones.setText("Consultar vacaciones");

        consultarEmergencia.setText("Concultar emergencia atendidas");

        consultarTurnos.setText("Concultar mis turnos");

        solicitarCambioTurno.setText("Solicitar cambio de turno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultarVacaciones)
                            .addComponent(consultarDatos)
                            .addComponent(consultarEmergencia)
                            .addComponent(consultarTurnos)
                            .addComponent(solicitarCambioTurno))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(consultarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultarVacaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultarEmergencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultarTurnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(solicitarCambioTurno)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void consultarDatosActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // Ne fait rien
    }           
    
    private void consultarVacacionesActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // Ne fait rien
    }                 
    
    /* A modifier quand nom de la 4e partie
    private void attenderLlamadaActionPerformed(){
    JFrame frame = new JFrame("Concultar emergencia atendidas");
        frame.setContentPane(new Vista####());
        frame.pack();
        frame.setVisible(true);
    }
    */      
    
    private void consultarTurnosActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // Ne fait rien
    }           

    private void solicitarCambioTurnoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // Ne fait rien
    }   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarDatos;
    private javax.swing.JButton consultarEmergencia;
    private javax.swing.JButton consultarTurnos;
    private javax.swing.JButton consultarVacaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton solicitarCambioTurno;
    // End of variables declaration//GEN-END:variables
}
