/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.disenosoftwareproject.interfaz.pares_vista_control;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class VistaGerente extends javax.swing.JPanel {

    public VistaGerente(String rol) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        consultarDatos = new javax.swing.JButton();
        consultarVacaciones = new javax.swing.JButton();
        organizarOperador = new javax.swing.JButton();
        modificarOperador = new javax.swing.JButton();
        organizarOperatorEmergencia = new javax.swing.JButton();

        jLabel1.setText("Gerente");

        consultarDatos.setText("Consultar mis datos en la empresa");
        consultarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarDatosActionPerformed(evt);
            }
        });

        consultarVacaciones.setText("Consultar vacaciones");
        consultarVacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVacacionesActionPerformed(evt);
            }
        });

        organizarOperador.setText("Organizar turnos de operador");
        organizarOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizarOperadorActionPerformed(evt);
            }
        });

        modificarOperador.setText("Modificar operador en turno");
        modificarOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarOperadorActionPerformed(evt);
            }
        });

        organizarOperatorEmergencia.setText("Organizar turnos de operativos de emergencia");
        organizarOperatorEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizarOperatorEmergenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultarVacaciones)
                            .addComponent(consultarDatos)
                            .addComponent(organizarOperador)
                            .addComponent(modificarOperador)
                            .addComponent(organizarOperatorEmergencia))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(consultarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultarVacaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(organizarOperador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificarOperador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(organizarOperatorEmergencia)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void consultarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarDatosActionPerformed
        // Ne fait rien
    }//GEN-LAST:event_consultarDatosActionPerformed

    private void consultarVacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVacacionesActionPerformed
        // Ne fait rien
    }//GEN-LAST:event_consultarVacacionesActionPerformed

    private void organizarOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizarOperadorActionPerformed
        JFrame frame = new JFrame("Modificar Operador en Turno");
        frame.setContentPane(new VistaModificarOperadorEnTurno());
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_organizarOperadorActionPerformed

    private void modificarOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarOperadorActionPerformed
        // Ne fait rien
    }//GEN-LAST:event_modificarOperadorActionPerformed

    private void organizarOperatorEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizarOperatorEmergenciaActionPerformed
        // Ne fait rien
    }//GEN-LAST:event_organizarOperatorEmergenciaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarDatos;
    private javax.swing.JButton consultarVacaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modificarOperador;
    private javax.swing.JButton organizarOperador;
    private javax.swing.JButton organizarOperatorEmergencia;
    // End of variables declaration//GEN-END:variables
}
