/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.disenosoftwareproject.interfaz.pares_vista_control;
import com.mycompany.disenosoftwareproject.negocio.modelos;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.io.IOException;

public class VistaRegistrarse extends javax.swing.JPanel {

    public VistaRegistrarse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JButton();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Identificador");

        jLabel2.setText("Contraseña");

        iniciarSesion.setText("Iniciar sesión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel2))
                                .addComponent(jTextField2))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(iniciarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iniciarSesion)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) throws JSONException, IOException {
        String identificador = jTextField1.getText();
        String contrasena = jTextField2.getText();

        if (identificador.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean isAuthenticated = false;
            String rol = "";

            // Lire le fichier JSON
            String content = new String(Files.readAllBytes(Paths.get("AChanger.json")));
            JSONArray empleados = new JSONArray(content);

            for (int i = 0; i < empleados.length(); i++) {
                JSONObject empleado = empleados.getJSONObject(i);
                if (empleado.getString("identificador").equals(identificador) &&
                    empleado.getString("contrasena").equals(contrasena)) {
                    isAuthenticated = true;
                    rol = empleado.getString("rol");
                    break;
                }
            }

            if (isAuthenticated) {
                switch (rol) {
                    case "gerente":
                        JOptionPane.showMessageDialog(this, "Acceso concedido. Rol: Gerente", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
                        // Ouvrir la vue GerenteView
                        VistaGerente gerenteView = new Gerente();
                        // Code pour afficher la vue GerenteView
                        break;
                    case "operador":
                        JOptionPane.showMessageDialog(this, "Acceso concedido. Rol: Operador", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
                        // Ouvrir la vue OperadorView
                        ViewOperador operadorView = new Operador();
                        // Code pour afficher la vue OperadorView
                        break;
                    case "medico":
                    case "conductor":
                        JOptionPane.showMessageDialog(this, "Acceso concedido. Rol: Personal de Operativo", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
                        // Ouvrir la vue PersonalDeOperativoView
                        ViewPersonalDeOperativo personalDeOperativoView = new PersonalDeOperativo();
                        // Code pour afficher la vue PersonalDeOperativoView
                        break;
                    default:
                        JOptionPane.showMessageDialog(this, "Rol desconocido.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Identificador o contraseña incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
